### ISSUE TITLE
[Feature request] Tree shaking

### ISSUE THREAD

**Issue by axeldelafosse** [nissy-dev/swc-plugin-react-native-web#31]
Hey @nissy-dev,

Thank you so much for your work! This SWC plugin is much needed!

The babel plugin also helps to reduce the bundle size by tree shaking: it is removing all the unused code from React Native for Web. It could be very helping to port this feature to the SWC plugin.

Any plans to make this happen?

Thanks,
Axel

**Comment by nissy-dev** [comment]
Thank you for feature requests!

My SWC plugin is almost same as the original babel plugin. The only different point is this plugin is not supported with importing react-native module with commonjs like [this test case](https://github.com/necolas/react-native-web/blob/fa47f80d34ee6cde2536b2a2241e326f84b633c4/packages/babel-plugin-react-native-web/src/__tests__/index-test.js#L43-L66). I didn't understand what you wanted me to do in the term of tree shaking.

And then, I think the babel-plugin-react-native-web (also, this plugin) is not necessary in many cases in the term of tree shaking. Generally, bundler (esbuild, webpack) perform tree shaking, not transpiler like babel and swc.
Actually, I confirmed removing all the unused code from react-native-web about the next.js example without using `babel-plugin-react-native-web`. There are same discussion, see https://github.com/necolas/react-native-web/discussions/2217. The total module size is 70.3kB, but the bundled size is only 14kB.   

<img width="1437" alt="SS_ 2022-12-10 19 19 41" src="https://user-images.githubusercontent.com/17228098/206849834-a158783b-c6dd-424d-9bc0-7d11acfecb0e.png">

bundlephobia also said that react-native-web package is tree shakeable.
https://bundlephobia.com/package/react-native-web@0.18.10
